global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 10
  height: 10
  origin_x: 5
  origin_y: 5
  static_map: false
  rolling_window: true
  inflation_radius: 0.35
  resolution: 0.01
